"""empty message

Revision ID: 714e58bcbe07
Revises: 5a731c4abcbc
Create Date: 2023-02-20 18:55:09.287829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "714e58bcbe07"
down_revision = "5a731c4abcbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Show", schema=None) as batch_op:
        batch_op.drop_column("start_time")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Show", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "start_time",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
