"""empty message

Revision ID: e7f4b4d8d0df
Revises: a6ae1ca4ac2d
Create Date: 2023-02-20 17:31:18.349859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f4b4d8d0df'
down_revision = 'a6ae1ca4ac2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    op.create_table('Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Genre_pkey')
    )
    # ### end Alembic commands ###
